package cmd

import (
	"fmt"
	"mault/internal/crypto"
	"mault/internal/storage"
	"mault/internal/storage/base"
	"mault/internal/storage/secret"

	"github.com/urfave/cli/v2"
	"gorm.io/gorm"
)

var generateC *cli.Command = &cli.Command{
	Name:  "generate",
	Usage: "generates a strong secret for you",
	Args:  false,
	Action: func(ctx *cli.Context) error {
		db, err := storage.AccessDatabase()
		if err != nil {
			return fmt.Errorf("accessing the database error: %v", err)
		}

		if !base.IsInitialized(db) {
			return fmt.Errorf("you haven't initialized the mault yet")
		}

		return GenerateSecret(db)
	},
}

func GenerateSecret(db *gorm.DB) error {
	var key string
	var autoGeneratedPassword []byte
	fmt.Print("Enter the name of the secret: ")
	_, err := fmt.Scanln(&key)
	if err != nil {
		return fmt.Errorf("could not scan the key: %v", err.Error())
	}

	for {
		var choice string
		autoGeneratedPassword, err = secret.GenerateRandom(16)
		if err != nil {
			return fmt.Errorf("generating password error: %v", err)
		}

		fmt.Println("The auto generated secret for you is: ", string(autoGeneratedPassword))
		for choice != "y" && choice != "n" {
			fmt.Printf("Approve? (y/n) ")
			fmt.Scanln(&choice)
		}
		if choice == "y" {
			break
		}
	}

	master, err := crypto.ReadPassword("master password")
	if err != nil {
		return fmt.Errorf("reading password error: %v", err)
	}

	salt, err := base.GetSalt(db)
	if err != nil {
		return fmt.Errorf("getting salt error: %v", err)
	}

	derivedKey := crypto.GenerateDerivedKey(master, salt)

	if !base.IsMatch(db, derivedKey) {
		return fmt.Errorf("authentication failed")
	}

	nonce, ciphertext, err := crypto.EncryptWithAESGCM(autoGeneratedPassword, derivedKey)
	if err != nil {
		return fmt.Errorf("encryption error: %v", err)
	}

	if err := secret.Create(db, secret.Secret{
		Key:        key,
		Nonce:      nonce,
		CipherText: ciphertext,
	}); err != nil {
		return fmt.Errorf("creating secret error: %v", err)
	}

	fmt.Println("Secret has created successfully!")
	return nil
}
